/**
 * 全角色資料表（目前 100 名；char_013 起為預留位，可替換名稱／數值與圖檔）
 * 會掛在 window.POCKET_PAWNS_CHARACTERS，供 game.js 讀取。
 *
 * 台詞／情境對話統一於 dialogueData.json（menuSelect、battleOpen、victory、defeat 等），勿在此重複撰寫。
 * 未在 JSON 內單獨填寫的角色會沿用 _default 與 getDialogueForCharacter 的後備字串。
 *
 * @typedef {{ id: string, name: string, sortIndex: number, initial: { stats: number[], hearts: number, maxHearts: number } }} PocketCharacter
 */


/** @type {PocketCharacter[]} */
window.POCKET_PAWNS_CHARACTERS = [
  {
    id: "char_001",
    name: "是阿茶啦",
    sortIndex: 1,
    initial: { stats: [1, 2, 8, 4, 12, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_002",
    name: "紅妻",
    sortIndex: 2,
    initial: { stats: [8, 11, 6, 5, 9, 2], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_003",
    name: "窮奇貓奇奇",
    sortIndex: 3,
    initial: { stats: [8, 10, 5, 5, 7, 5], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_004",
    name: "雲姬",
    sortIndex: 4,
    initial: { stats: [9, 9, 6, 6, 6, 4], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_005",
    name: "阿卡貓",
    sortIndex: 5,
    initial: { stats: [7, 7, 12, 4, 5, 5], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_006",
    name: "莎莉醬",
    sortIndex: 6,
    initial: { stats: [6, 14, 4, 5, 9, 2], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_007",
    name: "Moonlight",
    sortIndex: 7,
    initial: { stats: [5, 8, 5, 12, 7, 3], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_008",
    name: "神阪かんざか",
    sortIndex: 8,
    initial: { stats: [7, 10, 5, 6, 11, 1], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_009",
    name: "羅芝芝",
    sortIndex: 9,
    initial: { stats: [12, 6, 13, 8, 4, 9], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_010",
    name: "暴豆豆",
    sortIndex: 10,
    initial: { stats: [11, 5, 10, 3, 4, 7], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_011",
    name: "陽月芒果",
    sortIndex: 11,
    initial: { stats: [11, 1, 12, 9, 6, 2], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_012",
    name: "鎧鎧です",
    sortIndex: 12,
    initial: { stats: [3, 2, 3, 5, 3, 10], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_013",
    name: "陌祤彤",
    sortIndex: 13,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_014",
    name: "死者書生",
    sortIndex: 14,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_015",
    name: "Smile mitea",
    sortIndex: 15,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_016",
    name: "時櫻羽入",
    sortIndex: 16,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_017",
    name: "蒼月嵐",
    sortIndex: 17,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_018",
    name: "錫塔",
    sortIndex: 18,
    initial: { stats: [5, 4, 7, 8, 5, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_019",
    name: "十人",
    sortIndex: 19,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_020",
    name: "采彩",
    sortIndex: 20,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_021",
    name: "麋安",
    sortIndex: 21,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_022",
    name: "封",
    sortIndex: 22,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_023",
    name: "森雨悠娜",
    sortIndex: 23,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_024",
    name: "維尼",
    sortIndex: 24,
    initial: { stats: [12, 10, 9, 9, 2, 13], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_025",
    name: "櫻喵",
    sortIndex: 25,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_026",
    name: "思提莫莫",
    sortIndex: 26,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_027",
    name: "木夢",
    sortIndex: 27,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_028",
    name: "愛奧莉娜",
    sortIndex: 28,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_029",
    name: "陌祤彤",
    sortIndex: 29,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_030",
    name: "夜色守望",
    sortIndex: 30,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_031",
    name: "靜永月",
    sortIndex: 31,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_032",
    name: "火焰炎",
    sortIndex: 32,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_033",
    name: "蒼翎",
    sortIndex: 33,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_034",
    name: "圈圈",
    sortIndex: 34,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_035",
    name: "幼稚小孩巧可",
    sortIndex: 35,
    initial: { stats: [12, 5, 9, 6, 10, 7], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_036",
    name: "荻珥",
    sortIndex: 36,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_037",
    name: "煙米子二世",
    sortIndex: 37,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_038",
    name: "歌姬",
    sortIndex: 38,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_039",
    name: "Yaka",
    sortIndex: 39,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_040",
    name: "Yaka",
    sortIndex: 40,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_041",
    name: "勘紫",
    sortIndex: 41,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_042",
    name: "小親王",
    sortIndex: 42,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_043",
    name: "珀晞",
    sortIndex: 43,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_044",
    name: "彈跳櫻花蝦",
    sortIndex: 44,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_045",
    name: "非人類非動物",
    sortIndex: 45,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_046",
    name: "今夜橘子",
    sortIndex: 46,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_047",
    name: "春霞",
    sortIndex: 47,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_048",
    name: "藍凝燄",
    sortIndex: 48,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_049",
    name: "森奈",
    sortIndex: 49,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_050",
    name: "揪似艾",
    sortIndex: 50,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_051",
    name: "盧艾可",
    sortIndex: 51,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_052",
    name: "靈玉",
    sortIndex: 52,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_053",
    name: "莫莫兔菇",
    sortIndex: 53,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_054",
    name: "胡漢斯",
    sortIndex: 54,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_055",
    name: "阿卡咪",
    sortIndex: 55,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_056",
    name: "虹",
    sortIndex: 56,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_057",
    name: "緋櫻櫻",
    sortIndex: 57,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_058",
    name: "勘紫",
    sortIndex: 58,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_059",
    name: "雷森",
    sortIndex: 59,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_060",
    name: "神阪かんざか",
    sortIndex: 60,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_061",
    name: "落羽",
    sortIndex: 61,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_062",
    name: "芙卡咪小葵",
    sortIndex: 62,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_063",
    name: "夏西夏井",
    sortIndex: 63,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_064",
    name: "柯爾施",
    sortIndex: 64,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_065",
    name: "水御風",
    sortIndex: 65,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_066",
    name: "姜紫嫣",
    sortIndex: 66,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_067",
    name: "睫毛貓頭鷹",
    sortIndex: 67,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_068",
    name: "睫毛",
    sortIndex: 68,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_069",
    name: "陳警官",
    sortIndex: 69,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_070",
    name: "吳傑森",
    sortIndex: 70,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_071",
    name: "陌",
    sortIndex: 71,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_072",
    name: "泠",
    sortIndex: 72,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_073",
    name: "花知曉",
    sortIndex: 73,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_074",
    name: "水牽",
    sortIndex: 74,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_075",
    name: "霜星沁玥 ",
    sortIndex: 75,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_076",
    name: "羅塔塔",
    sortIndex: 76,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_077",
    name: "李夏",
    sortIndex: 77,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_078",
    name: "向尋",
    sortIndex: 78,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_079",
    name: "金穗",
    sortIndex: 79,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_080",
    name: "死者書生",
    sortIndex: 80,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_081",
    name: "彌",
    sortIndex: 81,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_082",
    name: "靜永月",
    sortIndex: 82,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_083",
    name: "米菲斯",
    sortIndex: 83,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_084",
    name: "水母暮暮",
    sortIndex: 84,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_085",
    name: "斯洛姆",
    sortIndex: 85,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_086",
    name: "若泉",
    sortIndex: 86,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
     id: "char_087",
    name: "咖啡歐",
    sortIndex: 87,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_088",
    name: "茶抹抹",
    sortIndex: 88,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_089",
    name: "nanagi",
    sortIndex: 89,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_090",
    name: "曉火",
    sortIndex: 90,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_091",
    name: "扇子",
    sortIndex: 91,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_092",
    name: "律豆豆",
    sortIndex: 92,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_093",
    name: "猫島羽依",
    sortIndex: 93,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_094",
    name: "夜雪儿",
    sortIndex: 94,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_095",
    name: "一狗愛笛聲",
    sortIndex: 95,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_096",
    name: "吳津",
    sortIndex: 96,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_097",
    name: "阿牽",
    sortIndex: 97,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_098",
    name: "靈玉",
    sortIndex: 98,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_099",
    name: "破羽",
    sortIndex: 99,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_100",
    name: "李研",
    sortIndex: 100,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
  {
    id: "char_101",
    name: "豆豆",
    sortIndex: 101,
    initial: { stats: [6, 6, 6, 6, 6, 6], hearts: 2, maxHearts: 4 },
  },
];





